<?php
// $Id$

/**
* Display help and module information
*/
function simplepicasa_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#simplepicasa":
      $output = '<p>'.  t("Help for simple picasa") .'</p>';
      break;
  }
  return $output;
}


/**
* Administration settings
*/
function simplepicasa_admin() {
  $form = array();
  $form['account'] = array(
    '#type' => 'fieldset',
    '#title' => t('Required settings'),
  );
  $form['account']['simplepicasa_username'] = array(
    '#type' => 'textfield',
    '#title' => t('Your Picasa Web username'),
    '#default_value' => variable_get('simplepicasa_username', ''),
    '#size' => 35,
    '#maxlength' => 35,
    '#description' => t("Please enter your Google Picasa Web username."),
    '#required' => TRUE,
  );
  return system_settings_form($form);
}


/**
* Valid permissions for this module
*/
function onthisdate_perm() {
  return array('access picasa gallery', 'administer simple picasa');
}


/**
* Menu for this module
*/
function simplepicasa_menu() {
  $items = array();
  $items['admin/settings/simplepicasa'] = array(
    'title' => 'Simple Picasa',
    'description' => 'Settings for Picasa Web module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('simplepicasa_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
   );
  return $items;
}
